### ISSUE TITLE
[Feature] Support Vuejs

### ISSUE THREAD

**Issue by TuanHaTMS** [HiPhish/nvim-ts-rainbow2#13]
Hi, can you add support for vue js with typescript.
Really love this plugin, Thanks!!

**Comment by HiPhish** [comment]
I don't know enough about Vue to do it myself, but if you help me out we might be able to make it work. From my understanding a Vue file contains one or more of the tags `<script>`, `<template>` and `<style>`, each of which contains either Javacript/Typescript, HTML or CSS respectively. Is this correct?

If so, then an empty query should be enough, the other language grammars would take over from there. Can you please provide me with an exhaustive Vue script file that covers all the cases? Then I could try and see if an empty query does the trick.

**Comment by tuanha168** [comment]
@HiPhish 
Hi, I created a PR for vuejs, can you check it ?
#14

**Comment by HiPhish** [comment]
Closing this issue as resolved
