### ISSUE TITLE
Some inner brackets are not highlighted

### ISSUE THREAD

**Issue by TroySigX** [HiPhish/nvim-ts-rainbow2#15]
**Describe the bug**

I have the following code written in TypeScript:
``` typescript
export function flipColors(c: number[]): number[] {
  return c.map((channel, id) => Math.floor((c[(id + 1) % 3] + c[(id + 2) % 3]) / 2));
}
```
I notice that the inner brackets (parentheses covering `id + 1` and `id + 2` aren't colored)

Here is my config:
``` lua
local rainbow = require 'ts-rainbow'

require('nvim-treesitter.configs').setup({
    rainbow = {
        enable = true,
        query = {
           'rainbow-parens'
        },
        extended_mode = true,
        strategy = rainbow.strategy.global,
        hlgroups = {
           'TSRainbowBlue',
           'TSRainbowViolet',
           'TSRainbowOrange',
           'TSRainbowGreen',
           'TSRainbowYellow',
           'TSRainbowRed',
           'TSRainbowCyan',
        },
    }
})
```
My color theme is `gruvbox-material`

**Screenshots**
![image](https://user-images.githubusercontent.com/88051085/225160204-4ef5ad6a-059d-4825-81f7-3ab0f298943b.png)

**Comment by HiPhish** [comment]
It should be fixed now on `master`. The issue was a missing pattern for `parenthesized_expression` in the Javascript query (the Typescript query inherits from the Javascript one).

**Comment by TroySigX** [comment]
Thanks for your quick action!
