### ISSUE TITLE
Error on startup (neovim 0.9)

### ISSUE THREAD

**Issue by meinside** [HiPhish/nvim-ts-rainbow2#23]
**Describe the bug**

I see following message occasionally:

```
Failed to run `config` for nvim-treesitter
...ocal/share/nvim/lazy/nvim-ts-rainbow2/lua/ts-rainbow.lua:18: loop or previous error loading module 'ts-rainbow.lib'
# stacktrace:
  - .config/nvim/init.lua:26 _in_ **config**
  - lua:1
  - vim/_editor.lua:0 _in_ **cmd**
Press ENTER or type command to continue
  - .config/nvim/init.lua:16
Press ENTER or type command to continue
Failed to source `/home/ubuntu/.local/share/nvim/lazy/nvim-ts-rainbow2/plugin/rainbow.vim`
vim/_editor.lua:0: /home/ubuntu/.config/nvim/init.lua..nvim_exec2() called at /home/ubuntu/.config/nvim/init.lua:0../home/ubuntu/.local/share/nvim/lazy/nvim-ts
-rainbow2/plugin/rainbow.vim, line 25: Vim(lua):E5108: Error executing lua ...are/nvim/lazy/nvim-ts-rainbow2/lua/ts-rainbow/module.lua:19: loop or previous err
or loading module 'ts-rainbow'
stack traceback:
^I[C]: in function 'require'
^I...are/nvim/lazy/nvim-ts-rainbow2/lua/ts-rainbow/module.lua:19: in main chunk
^I[C]: in function 'require'
^I[string ":lua"]:1: in main chunk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:438: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:437>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:110: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:437: in function 'source'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:396: in function 'source_runtime'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:364: in function 'packadd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:304: in function '_load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:180: in function 'load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:115: in function 'startup'
^I...buntu/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:85: in function 'setup'
^I/home/ubuntu/.config/nvim/init.lua:16: in main chunk
# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
Press ENTER or type command to continue
```

It does not occur every time, but I see it quite often.

Tried bisecting and the first bad commit is 93a5bc960094aa6baf60bfa4894545d4d66ec13e.

Tested on neovim **v0.9.0-dev-1291+gbad218cd6**.

**Steps to reproduce**

Following is my minimum reproducible init.lua file:

```lua
-- reproducible .config/nvim/init.lua

local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require'lazy'.setup({
  { 'HiPhish/nvim-ts-rainbow2' },
  {
    'nvim-treesitter/nvim-treesitter', config = function()
      require'nvim-treesitter.configs'.setup {
        highlight = { enable = true },
        rainbow = {
          enable = true,
          extended_mode = true,
          query = 'rainbow-parens',
          strategy = require'ts-rainbow'.strategy.global,
        },
      }
    end,
  },
})
```

**Expected behavior**

There should be no error message about this plugin.

**Screenshots**

<img width="839" alt="Screenshot 2023-03-28 at 14 30 57" src="https://user-images.githubusercontent.com/185988/228137520-86bc2a59-4e75-49a0-8133-1daf5d5c5c5e.png">
<img width="1116" alt="Screenshot 2023-03-28 at 14 37 30" src="https://user-images.githubusercontent.com/185988/228138572-5794e88f-37b5-4e7c-8ff2-92345bd7c3aa.png">

**Comment by gregorias** [comment]
I have the same error in v0.8.3.

**Comment by HiPhish** [comment]
My guess is that there might be a weird `require` loop because you are loading the strategy directly. Try changing your rainbow settings to something like this:

```lua
local rb = require 'ts-rainbow'

rainbow = {
    enable = true,
    query = 'rainbow-parens',
    strategy = rb.strategy.global,
}
```

With this all the modules should get loaded in the correct order. Note also that I removed the `extended_mode` setting since it does not apply to this plugin (it doesn't hurt either though).

**Comment by meinside** [comment]
Sorry to say but your suggestion doesn't make much difference, it still occurs occasionally.
When I try 10 times, I see it two or three times in average, and the frequency doesn't seem to have changed.

**Comment by HiPhish** [comment]
I have added a source guard to the plugin, this should prevent the editor from sourcing the plugin multiple times. Can you please try out the current `master` branch?

**Comment by meinside** [comment]
Thank you for your effort, but it's still happening here.

Is there anything I can do or test for you? I'm sticking with v2.1.0, so it is not an urgent matter for me.

**Comment by HiPhish** [comment]
I really cannot see where the problem could be coming from. Here is something you can do: add a unique `print` call at the top of each Lua source file. You could for example print the name of the file. That should give us a trail through which file is loaded when.

**Comment by gregorias** [comment]
My *guess* is that this is caused by having a module loading loop. My hot-fix was to make ts-rainbow2 lazy:

```
-- reproducible .config/nvim/init.lua

local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require'lazy'.setup({
  { 'HiPhish/nvim-ts-rainbow2', lazy = true },
  {
    'nvim-treesitter/nvim-treesitter',
    dependencies = { "HiPhish/nvim-ts-rainbow2", }
    config = function()
      require'nvim-treesitter.configs'.setup {
        highlight = { enable = true },
        rainbow = {
          enable = true,
          extended_mode = true,
          query = 'rainbow-parens',
          strategy = require'ts-rainbow'.strategy.global,
        },
      }
    end,
  },
})
```

IMO, the README.md should describe the correct setup with Lazy to avoid this error.

**Comment by HiPhish** [comment]
> My guess is that this is caused by having a module loading loop.

That is my guess as well, but I cannot figure out where that look is supposed to come from. If we look at the code, the source order is as follows:

- `plugin/rainbow.vim`
- `lua/ts-rainbow/module.lua`
- `lua/ts-rainbow/lib.lua`
- `lua/ts-rainbow.lua`

The last file depends on `lib.lua`, but requiring the same file multiple times is fine.


> IMO, the README.md should describe the correct setup with Lazy to avoid this error.

Lazy is non-standard, so it is up to Lazy and its users to set up Lazy correctly. I can and will try to make ts-rainbow work nicely with package managers as best as I can, but the only truly supported way of using a plugin is the canonical standard features.

**Comment by meinside** [comment]
Now it's okay after applying gregorias' fix.
There seems to be a problem with lazy.nvim, so I'm closing this issue.
