### ISSUE TITLE
Feature Request: Add queries for Ruby

### ISSUE THREAD

**Issue by numbcoder** [HiPhish/nvim-ts-rainbow2#30]
Hi, Thanks for your work on this awesome plugin. 
Is there any plan to support ruby?

**Comment by HiPhish** [comment]
I don't know Ruby, so I will need help from someone. If you want to be that someone, here is what you need to do:

- Read `:h ts-rainbow-custom-lang`
- Read `CONTRIBUTING.rst`
- Write a short Ruby script which demonstrates all the different parts you want highlighted; the script does not have to be actually valid, but it would be cool if it was
- Write a query named `rainbow-parens.scm` with all the patterns you want to
  capture

It's a very straight-forward process. The hardest part is making sure you cover all the patterns you want to match.
