### ISSUE TITLE
Highlight level calculation too slow

### ISSUE THREAD

**Issue by HiPhish** [HiPhish/nvim-ts-rainbow2#4]
The current way of computing the highlight levels for matches is too slow. On
every change we first collect all matches into a tree-like structure and
allocate a lot of table in the process. These tables then immediately become
garbage that needs to be disposed of when done with the change.

Here are some rough ideas:

- Have a pool of reusable tables so we don't have to create new tables every
  time.
- Use a custom directive so we can associate a match and its parent within the
  match object instead of creating a new table. This still requires some sort
  of "stack" of nodes which have not yet been sorted, but we do not need to
  keep track of the entire tree.

These are just two ideas off the top of my head. I will have to try them out to
see what works and what does not.

**Comment by HiPhish** [comment]
I have found the bottleneck, it is not the allocation of tables as I had
initially suspected. In the global strategy there is a predicate function which
calls the `is_ancestor` function from the Tree-sitter module. Removing that
function call and replacing it with a hard-coded value (like `false` or `true`)
fixes performance.

```lua
local function is_child(other)
	return ts.is_ancestor(match_record.container, other.container)
end
````

This is inefficient because we end up comparing the current match with every
other match in the set of matches. LaTeX documents typically have a very wide
and shallow structure, meaning there are many nodes with little nesting and
thus we have a lot of comparisons going on.

I suspect that the solution will be to use a stack. Consider the following node
tree:

```
├─A
│ ├─B
│ └─C
│   ├─D
│   └─E
│     ├─F
│     └─G
├─H
│ ├─I
│ └─J
│   └─K
├─L
│ └─M
│   └─N
└─O
  └─P
    └─Q
      └─R
```

We can make use of the order of traversal (see `HACKING` file).

- Keep a stack of matches. The stack is initially empty
- For every match pop elements off the stack until we encounter the first stack
  element which is not a child of the current match.
- All the popped elements are direct children of the current match
- Push the current match to the top of the stack

This means that we only need to check for a child-parent relationship, not a
general descendant-ancestor relationship. In general this will reduce the
amount of checks because we have a clear cut-off point.

However, the benefit to LaTeX files will still be limited. A flat hierarchy
means that one node can have potentially a lot of direct children, and they
will all be checked. Still, it will be much more efficient than what we have
now.

**Comment by HiPhish** [comment]
@mathjiajia Can you please test the current `master`? Performance should be much better now. For me, I can no longer notice any difference when opening the LaTeX file.

**Comment by mathjiajia** [comment]
> @mathjiajia Can you please test the current `master`? Performance should be much better now. For me, I can no longer notice any difference when opening the LaTeX file.

Thanks. After testing I think you have resolved this performance issue.

**Comment by HiPhish** [comment]
Closing this as resolved then. Thank you for bringing up the issue.

**Comment by HiPhish** [comment]
Hi,

see `:h ts-rainbow-colors` in the manual for how to specify colours; this fork uses highlight groups instead of hex colour codes. Why highlight groups? Because that is the Vim way.

- Highlight groups are used throughout the Vim and Neovim functions
- We can support both true colour (GUI) and colour terminals
- We can link to existing highlight groups from colour schemes
- We get support for switching colour schemes on the fly for free.
- We can make use of all the highlight group properties, such as underlining or italics

Even the original plugin was using highlight groups internally. Here is an example of how you can get what you want:

```lua
-- First we have to redefine the highlight groups
vim.api.nvim_set_hl(0, 'TSRainbowRed',    {fg = 'royalblue3'})
vim.api.nvim_set_hl(0, 'TSRainbowYellow', {fg = 'darkorange3'})
vim.api.nvim_set_hl(0, 'TSRainbowBlue',   {fg = 'seagreen3'})
vim.api.nvim_set_hl(0, 'TSRainbowOrange', {fg = 'firebrick'})
vim.api.nvim_set_hl(0, 'TSRainbowGreen',  {fg = 'darkorchid3'})

-- Now we specify those five groups in the rainbow settings
require('nvim-treesitter.configs').setup {
    rainbow = {
        hlgroups = {
            `TSRainbowRed`,
            `TSRainbowYellow`,
            `TSRainbowBlue`,
            `TSRainbowOrange`,
            `TSRainbowGreen`,
        }
    }
}
```

You don't have to use the `TSRainbow...` groups, you can used whatever highlight groups you want if you already have some that you want to reuse.

If this answers your question please close the issue.
