### ISSUE TITLE
add matlab language supoort

### ISSUE THREAD

**Issue by 396458015** [HiPhish/nvim-ts-rainbow2#56]
### Description

```Text
This adds matlab language support
```

**Comment by HiPhish** [comment]
Did you meant to open a pull request instead? If so, please open it over on https://github.com/HiPhish/rainbow-delimiters.nvim/ instead, this plugin is deprecated.

**Comment by 396458015** [comment]
> Did you meant to open a pull request instead? If so, please open it over on https://github.com/HiPhish/rainbow-delimiters.nvim/ instead, this plugin is deprecated.

Okay, thanks for reply
