### ISSUE TITLE
[Bug]: color doesn't change

### ISSUE THREAD

**Issue by MKrbm** [HiPhish/nvim-ts-rainbow2#58]
### Neovim version

0.9.1

### Language affected

cpp

### Description

```Text
The plugin change the parenthesis colors for lua but c, cpp.
Do I need to set-up another Query?
```

**Comment by HiPhish** [comment]
This plugin is deprecated, please use https://github.com/HiPhish/rainbow-delimiters.nvim instead. Please report the issue there if it still persists.

**Comment by MKrbm** [comment]
Thank you ! 
It worked fine.
