### ISSUE TITLE
[Bug]: LanguageTree:for_each_child is deprecated

### ISSUE THREAD

**Issue by n3wborn** [HiPhish/nvim-ts-rainbow2#59]
### Neovim version

v0.10.0-dev-1105+g2e9206568

### Description

```Text
Since neovim#25118, LanguageTree:for_each_child is deprecated

Simply open a file and see the deprecation notification
```

**Comment by n3wborn** [comment]
![deprecation](https://github.com/HiPhish/nvim-ts-rainbow2/assets/10246722/71c609e8-0462-4c36-99f9-4b3396d15eef)

**Comment by HiPhish** [comment]
This plugin is deprecated, please use https://github.com/HiPhish/rainbow-delimiters.nvim instead.
