### ISSUE TITLE
Doesn't work like the original

### ISSUE THREAD

**Issue by pseudoparenchymatous** [HiPhish/nvim-ts-rainbow2#9]
Doesn't this plugin setup the same way as [the original](https://github.com/p00f/nvim-ts-rainbow)? I replaced one line in my config but it doesn't work.
![IMG_20230221_015414](https://user-images.githubusercontent.com/105337186/220174413-a0befe97-ffcc-4438-aac0-9f01fe9b7c33.jpg)
![IMG_20230221_015350](https://user-images.githubusercontent.com/105337186/220174398-56781277-57d5-4946-86cd-059d5d9e676c.jpg)

**Comment by HiPhish** [comment]
Have you enabled the nvim-treesitter module? Here is what a minimal config looks like:

```lua
require'nvim-treesitter.configs'.setup {
	-- Other stuff before...
	rainbow = {
		enable = true,
	},
	-- Other stuff after...
}
```

If I don't enable the module nothing happens for me either. If you have enabled the module, which language is it that's not working? I don't have support for all the languages from the original because the query format is completely different. Contributions for more languages are always welcome.

**Comment by pseudoparenchymatous** [comment]
Like I said, I only replaced one line in my nvim config (so this is in lua). I didn't modify the part of my config where I enabled p00f's version after replacing rainbow with rainbow2 since they're supposed to be enabled the same way.

Manually enabling it with `:lua require('nvim-treesitter.configs').setup({ rainbow = { enable = true} })` in the nvim cmdline also doesn't work.

**Comment by HiPhish** [comment]
Which languages have you tried? Do you have the corresponding grammar 
installed?

**Comment by pseudoparenchymatous** [comment]
Bruh how is it suddenly working 😭. Istg I didn't change anything but now it works. Though it's using a brighter set of colors than my colorscheme (2nd pic). I can live with it for now. Anyway, thanks for the amazing work! You're awesome! 

![IMG_20230221_015414](https://user-images.githubusercontent.com/105337186/220554860-d6405340-6b2d-435d-ba49-f5d364b928af.jpg)

![IMG_20230222_154142](https://user-images.githubusercontent.com/105337186/220554975-40b06d64-b798-4448-a197-62c06987b554.jpg)
